version: '3.9'
services:
  sys.medical.api:
    image: sys.medical.api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=${CONNECTION_STRING}
      - Cors:Urls=${URLS_LIBERADAS}
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8282:8282
    expose:
      - 8282
    networks: 
      - teste

networks:
  teste:
    driver: bridge
    
